name: Build Kivy App to APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # نصب وابستگی‌های مورد نیاز برای Buildozer
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libtinfo5 libncurses5 wget unzip

      # دانلود و تنظیم NDK نسخه r21e
      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip android-ndk-r21e-linux-x86_64.zip
          echo "LEGACY_NDK=$PWD/android-ndk-r21e" >> $GITHUB_ENV

      # نصب Buildozer و Cython
      - name: Install Buildozer
        run: |
          pip install buildozer Cython==0.29.36

      # ساخت APK با استفاده از Buildozer
      - name: Build APK
        run: |
          buildozer -v android debug

      # آپلود خروجی APK به عنوان Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
